
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.prometheus.metrics.argoproj.io
  labels:
    api: argoproj-metrics-poc
    apiserver: "true"
spec:
  version: v1
  group: prometheus.metrics.argoproj.io
  groupPriorityMinimum: 2000
  service:
    name: argoproj-metrics-poc
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6RENDQXJTZ0F3SUJBZ0lVZDZWdHRHb08xZkwwMVl5ZXZEK1lqckVXdHFZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RERUxNQWtHQTFVRUJoTUNkVzR4Q3pBSkJnTlZCQWdNQW5OME1Rb3dDQVlEVlFRSERBRnNNUW93Q0FZRApWUVFLREFGdk1Rc3dDUVlEVlFRTERBSnZkVEV6TURFR0ExVUVBd3dxWVhKbmIzQnliMm90YldWMGNtbGpjeTF3CmIyTXRZMlZ5ZEdsbWFXTmhkR1V0WVhWMGFHOXlhWFI1TUI0WERUSXlNVEV4TmpBek1ERTBPVm9YRFRJek1URXgKTmpBek1ERTBPVm93ZERFTE1Ba0dBMVVFQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGcwpNUW93Q0FZRFZRUUtEQUZ2TVFzd0NRWURWUVFMREFKdmRURXpNREVHQTFVRUF3d3FZWEpuYjNCeWIyb3RiV1YwCmNtbGpjeTF3YjJNdFkyVnlkR2xtYVdOaGRHVXRZWFYwYUc5eWFYUjVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvOGhaemRTSnJjWnZ4aFhNdGNuVnJBdkxSZGhiZk42cWNpaHVKend6aDFCTQo0QkZLQ2tPdW04OG9ic0FvVjhaa3piVGFhSU9udGhWWGlycmxkMDIrZVJ2UDVyOXpCTm16WjE4RUFJb1dzWFRpCjg0STVOZ1dJdzFWZW1SbVZ6RGV4aEFjNnUva0hxbnJZdGRxazhhakRHd3ZtZko5TGFmZzhGRE1ZWThDek9NVXEKUmNua3dmbHlHVVNxYTQ4TWplQlMzNEprK1JkSE4vaXhCS1JpOEYxeTNhaFBhdThmaEpZS0M3UUxJU2J2MmNCNQpVOXZWRVdvdFdpbXJPRElFQTBDb20wSzZ4MHJ4ZmxxZEFpcE9pSkV0NVR3TEk4Q0JjMmN2UU1tOVlGdzZtUHFUCitCaUp5OW9vVSswTU1iT1NGdm1QaHcxNHpWaUVhUXByV0Z4VFV3em1rUUlEQVFBQm8xWXdWREFkQmdOVkhRNEUKRmdRVXgxUkRXTU41K1poNitzQ0s3TE5VMEtyZFphQXdId1lEVlIwakJCZ3dGb0FVeDFSRFdNTjUrWmg2K3NDSwo3TE5VMEtyZFphQXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCm5jck5Zc1pJcy9ZWlBSa0YwOTl3eTRPa2plRU9NRlJwb2YrMXlqSEpxbWNyU043MDJrTytDOUpkanR0QUVOMHAKcHhPbzd5VER2V3hHN1Noc1dDQzNyZkVjdERnREhqRFVmWGR1djZ1V2tiTnJ2eGhUSG5JUWU3L3Y5SkNKSUltSgpBalBnUDk5d2RmaUVDUkwyUm5jVFNzREFhNU5SL0tnQTR6Mm9wNE9zaDdRemlNL1E4RlhLZWVrWFU5ZDZ6M0NqCjIrOC9RNkVnMHNRY1ZJbGdQb3MrTGpJWnI3R01PUjd3allGalNHZW5Udm56eFowdUU4RUwvajI1eFVZazNyb1UKdXpDVzc5K1l1ZUdxN1VxNFZ0RzFER2RUQTNGVE14ODNyYzZpRTZKdFo3QjVOYVZ6YU9tYUxndE1KVGlKL0ZxbAo3YjZOd05MYWxvMXI5bEJxUjZ3OFhRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
---
