---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoproj-metrics-poc-controller
  namespace: default
  labels:
    api: argoproj-metrics-poc
    controller: "true"
spec:
  selector:
    matchLabels:
      api: argoproj-metrics-poc
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: argoproj-metrics-poc
        controller: "true"
    spec:
      containers:
      - name: controller
        image: zachaller/argoproj-metrics-poc
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: argoproj-metrics-poc
