---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - prometheus
  resources:
  - metricqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prometheus
  resources:
  - metricqueries/finalizers
  verbs:
  - update
- apiGroups:
  - prometheus
  resources:
  - metricqueries/status
  verbs:
  - get
  - patch
  - update
